# Generated by Django 5.2.13 on 2026-06-09 19:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fcreacion', models.DateTimeField(auto_now_add=True)),
                ('fmodificacion', models.DateTimeField(auto_now=True)),
                ('dni', models.CharField(max_length=8, verbose_name='DNI')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('apellidos', 'nombres'),
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fcreacion', models.DateTimeField(auto_now_add=True)),
                ('fmodificacion', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('FALTA', 'Falta')], max_length=10)),
                ('observacion', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ('-fecha',),
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fcreacion', models.DateTimeField(auto_now_add=True)),
                ('fmodificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fcreacion', models.DateTimeField(auto_now_add=True)),
                ('fmodificacion', models.DateTimeField(auto_now=True)),
                ('nivel', models.CharField(choices=[('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria')], max_length=12)),
                ('nombre', models.CharField(max_length=50)),
                ('seccion', models.CharField(max_length=10)),
                ('anio_academico', models.PositiveSmallIntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-anio_academico', 'nivel', 'nombre', 'seccion'),
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('codigo_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fcreacion', models.DateTimeField(auto_now_add=True)),
                ('fmodificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'institucion',
                'verbose_name_plural': 'instituciones',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fcreacion', models.DateTimeField(auto_now_add=True)),
                ('fmodificacion', models.DateTimeField(auto_now=True)),
                ('anio_academico', models.PositiveSmallIntegerField(editable=False)),
                ('fecha_matricula', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('RETIRADA', 'Retirada'), ('FINALIZADA', 'Finalizada')], default='ACTIVA', max_length=12)),
            ],
            options={
                'ordering': ('-anio_academico', 'alumno__apellidos'),
            },
        ),
        migrations.CreateModel(
            name='MatriculaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fcreacion', models.DateTimeField(auto_now_add=True)),
                ('fmodificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('curso__nombre',),
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fcreacion', models.DateTimeField(auto_now_add=True)),
                ('fmodificacion', models.DateTimeField(auto_now=True)),
                ('periodo', models.CharField(choices=[('1', 'Primer periodo'), ('2', 'Segundo periodo'), ('3', 'Tercer periodo'), ('4', 'Cuarto periodo')], max_length=1)),
                ('evaluacion', models.CharField(max_length=100)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
            ],
            options={
                'ordering': ('-fcreacion',),
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fcreacion', models.DateTimeField(auto_now_add=True)),
                ('fmodificacion', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('ASISTENCIA', 'Asistencia'), ('RENDIMIENTO', 'Rendimiento academico')], max_length=15)),
                ('nivel_riesgo', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], max_length=10)),
                ('descripcion', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='academico.alumno')),
            ],
            options={
                'ordering': ('-fcreacion',),
            },
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fcreacion', models.DateTimeField(auto_now_add=True)),
                ('fmodificacion', models.DateTimeField(auto_now=True)),
                ('dni', models.CharField(max_length=8, verbose_name='DNI')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('celular', models.CharField(max_length=9)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('parentesco', models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('TUTOR', 'Tutor legal'), ('OTRO', 'Otro')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('alumnos', models.ManyToManyField(blank=True, related_name='apoderados', to='academico.alumno')),
            ],
            options={
                'ordering': ('apellidos', 'nombres'),
            },
        ),
    ]
