# Generated by Django 5.2.14 on 2026-05-26 14:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('celular', models.CharField(blank=True, default='', max_length=9, null=True)),
                ('correo', models.EmailField(blank=True, default='', max_length=100, null=True)),
                ('rol', models.CharField(choices=[('DIRECTOR', 'Director'), ('PROFESOR', 'Profesor')], max_length=15)),
                ('activo', models.BooleanField(default=False)),
                ('codigo_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fcreacion', models.DateTimeField(auto_now_add=True)),
                ('fmodificaicon', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
