# Generated by Django 5.2.13 on 2026-06-09 19:29

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apoderado',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_apoderado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grado',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grados_tutoreados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='academico.grado'),
        ),
        migrations.AddField(
            model_name='grado',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.institucion'),
        ),
        migrations.AddField(
            model_name='curso',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.institucion'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.institucion'),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.institucion'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.institucion'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.institucion'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='academico.alumno'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='academico.grado'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.institucion'),
        ),
        migrations.AddField(
            model_name='matriculacurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas_curso', to='academico.curso'),
        ),
        migrations.AddField(
            model_name='matriculacurso',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.institucion'),
        ),
        migrations.AddField(
            model_name='matriculacurso',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos_matriculados', to='academico.matricula'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='matricula_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='academico.matriculacurso'),
        ),
        migrations.AddField(
            model_name='nota',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.institucion'),
        ),
        migrations.AddField(
            model_name='nota',
            name='matricula_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='academico.matriculacurso'),
        ),
        migrations.AddConstraint(
            model_name='grado',
            constraint=models.UniqueConstraint(fields=('institucion', 'anio_academico', 'nivel', 'nombre', 'seccion'), name='grado_unico_institucion_anio'),
        ),
        migrations.AddConstraint(
            model_name='curso',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('codigo'), models.F('institucion'), models.F('grado'), name='curso_codigo_unico_grado'),
        ),
        migrations.AddConstraint(
            model_name='curso',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), models.F('institucion'), models.F('grado'), name='curso_nombre_unico_grado'),
        ),
        migrations.AddConstraint(
            model_name='apoderado',
            constraint=models.UniqueConstraint(fields=('institucion', 'dni'), name='apoderado_dni_unico_institucion'),
        ),
        migrations.AddConstraint(
            model_name='alumno',
            constraint=models.UniqueConstraint(fields=('institucion', 'dni'), name='alumno_dni_unico_institucion'),
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('institucion', 'alumno', 'anio_academico'), name='matricula_unica_alumno_anio'),
        ),
        migrations.AddConstraint(
            model_name='matriculacurso',
            constraint=models.UniqueConstraint(fields=('matricula', 'curso'), name='matricula_curso_unica'),
        ),
        migrations.AddConstraint(
            model_name='asistencia',
            constraint=models.UniqueConstraint(fields=('matricula_curso', 'fecha'), name='asistencia_unica_alumno_curso_fecha'),
        ),
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.UniqueConstraint(fields=('matricula_curso', 'periodo', 'evaluacion'), name='nota_unica_evaluacion'),
        ),
    ]
