# Generated by Django 5.2.13 on 2026-06-06 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apoderado',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_apoderado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='academico.grado'),
        ),
        migrations.AddField(
            model_name='grado',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.institucion'),
        ),
        migrations.AddField(
            model_name='curso',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.institucion'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.institucion'),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.institucion'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.institucion'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.institucion'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='academico.alumno'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='academico.grado'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.institucion'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academico.matricula'),
        ),
        migrations.AddField(
            model_name='nota',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='academico.curso'),
        ),
        migrations.AddField(
            model_name='nota',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.institucion'),
        ),
        migrations.AddField(
            model_name='nota',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='academico.matricula'),
        ),
        migrations.AddConstraint(
            model_name='grado',
            constraint=models.UniqueConstraint(fields=('institucion', 'anio_academico', 'nivel', 'nombre', 'seccion'), name='grado_unico_institucion_anio'),
        ),
        migrations.AddConstraint(
            model_name='curso',
            constraint=models.UniqueConstraint(fields=('institucion', 'codigo', 'grado'), name='curso_codigo_unico_grado'),
        ),
        migrations.AddConstraint(
            model_name='apoderado',
            constraint=models.UniqueConstraint(fields=('institucion', 'dni'), name='apoderado_dni_unico_institucion'),
        ),
        migrations.AddConstraint(
            model_name='alumno',
            constraint=models.UniqueConstraint(fields=('institucion', 'dni'), name='alumno_dni_unico_institucion'),
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('institucion', 'alumno', 'anio_academico'), name='matricula_unica_alumno_anio'),
        ),
        migrations.AddConstraint(
            model_name='asistencia',
            constraint=models.UniqueConstraint(fields=('matricula', 'fecha'), name='asistencia_unica_matricula_fecha'),
        ),
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.UniqueConstraint(fields=('matricula', 'curso', 'periodo', 'evaluacion'), name='nota_unica_evaluacion'),
        ),
    ]
