# Generated by Django 5.2.13 on 2026-05-25 00:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('nombres', models.CharField(max_length=100, verbose_name='nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='apellidos')),
            ],
            options={
                'verbose_name': 'estudiante',
                'verbose_name_plural': 'estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('codigo_modular', models.CharField(max_length=20, unique=True, verbose_name='código modular')),
            ],
            options={
                'verbose_name': 'institución',
                'verbose_name_plural': 'instituciones',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='nota')),
                ('periodo', models.CharField(max_length=50, verbose_name='periodo')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones_registradas', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='academico.curso', verbose_name='curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='academico.estudiante', verbose_name='estudiante')),
            ],
            options={
                'verbose_name': 'calificación',
                'verbose_name_plural': 'calificaciones',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('estado', models.CharField(choices=[('asistio', 'Asistió'), ('falto', 'Faltó')], max_length=20, verbose_name='estado')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='academico.curso', verbose_name='curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='academico.estudiante', verbose_name='estudiante')),
            ],
            options={
                'verbose_name': 'asistencia',
                'verbose_name_plural': 'asistencias',
            },
        ),
        migrations.CreateModel(
            name='AlertaRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=20, verbose_name='nivel')),
                ('motivo', models.TextField(verbose_name='motivo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('esta_activa', models.BooleanField(default=True, verbose_name='está activa')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas_riesgo', to='academico.estudiante', verbose_name='estudiante')),
            ],
            options={
                'verbose_name': 'alerta de riesgo',
                'verbose_name_plural': 'alertas de riesgo',
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='academico.institucion', verbose_name='institución'),
        ),
    ]
