name: CI Pipeline

on:
  push:
    branches: [dev, main]   # Corre en ambas ramas
  pull_request:
    branches: [main]

jobs:
  test:
    name: Tests + Seguridad
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar tests
        run: python manage.py test

      - name: 🔒 Análisis de seguridad (Bandit)
        run: |
          pip install bandit
          bandit -r . -ll -ii --exclude ./tests,./venv

  deploy-dev:
    name: Deploy a Render Dev
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy a Render Dev
        run: curl -X POST "$https://api.render.com/deploy/srv-d7ok019o3t8c7381viog?key=0zuMNEbJcq8"
